spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: Accountify

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/accountify?createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}

  jpa:
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://securetoken.google.com/***REMOVED***
          audiences: ***REMOVED***

websiteUrl: http://localhost:8080
springdoc:
  swagger-ui:
    syntax-highlight:
      theme: obsidian

