spring:
  application:
    name: Accountify

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true

websiteUrl: http://localhost:8080
springdoc:
  swagger-ui:
    syntax-highlight:
      theme: obsidian

