ALTER TABLE business MODIFY timestamp BIGINT NOT NULL;
ALTER TABLE journal MODIFY timestamp BIGINT NOT NULL;
ALTER TABLE ledger MODIFY timestamp BIGINT NOT NULL;
ALTER TABLE bill MODIFY timestamp BIGINT NOT NULL;
ALTER TABLE entry MODIFY timestamp BIGINT NOT NULL;
ALTER TABLE bill_entry MODIFY timestamp BIGINT NOT NULL;
